
method: puat-pre
data_dir: ../dataset_data
log_dir: trained_models/baselines/cifar10

data: cifar10
take_amount: 4000
model: wrn-28-10-swish

num_epochs: 100
lr: 0.2
scheduler: cosinew
batch_size: 512
unsup_fraction: 0.5
batch_size_validation: 256
adv_eval_freq: 100
validation: false

alpha: 0.5
gamma: 0.03
lamb: 10.
beta: 6.
adv_ramp_start: 999
adv_ramp_end: 999
tau: 0.99
tau_after: 0.999
consistency_cost: 50
consistency_ramp_up: 30
mix_frac: 0.9
ls: 0.1

gan_start: 10
# arguments for G
g_model_name: resnet_sngan
g_z_dim: 256
g_nfilter: 32
g_nfilter_max: 256
g_actvn: relu
g_optim: adam
g_lr: 0.0001
g_beta1: 0.
g_beta2: 0.99
g_weight_decay: 0.

a_optim: adam
a_lr: 0.0001
a_beta1: 0.
a_beta2: 0.99
a_weight_decay: 0.
a_actvn: relu
a_embed_size: 256

# arguments for D
d_model_name: resnet_sngan
d_z_dim: 256
d_embed_size: 256
d_nfilter: 32
d_nfilter_max: 256
d_actvn: relu

d_optim: adam
d_lr: 0.0001
d_beta1: 0.
d_beta2: 0.99
d_weight_decay: 0.